# Generated by Django 3.2.7 on 2021-10-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyform',
            name='username',
            field=models.CharField(default='Sacchin Kulkarni', max_length=200),
            preserve_default=False,
        ),
    ]
