# Generated by Django 3.2.7 on 2021-10-06 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_storyform_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
