# Generated by Django 3.2.7 on 2021-10-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_storyform_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoryForm',
            new_name='Story',
        ),
    ]
