# Generated by Django 3.2.7 on 2021-10-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_rename_storyform_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='response',
            new_name='api_response',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='request',
            new_name='user_input',
        ),
    ]
