# Generated by Django 3.2.7 on 2021-10-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_auto_20211011_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='api_response',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
