# Generated by Django 3.2.7 on 2021-10-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_alter_story_api_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='api_response',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
